spring:
  application:
    name: simple-online-shop

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080